steps:
# Set the PR_BUILD flag
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [ "$_PR_BUILD" == "true" ]; then
      echo "true" > /workspace/PR_BUILD.txt
    else
      echo "false" > /workspace/PR_BUILD.txt
    fi
  id: 'set-pr-build-flag-staging'

# Build the frontend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--build-arg', 
    'ENVIRONMENT=staging',
    '--build-arg',
    'GOOGLE_ANALYTICS_ID=$_GOOGLE_ANALYTICS_ID', 
    '-t', 
    'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA', 
    './frontend/'
    ]
  id: 'build-frontend-image-staging'

# Push the frontend Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA']
  id: 'push-frontend-image-staging'

# Deploy the frontend to Google Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [ "$(cat /workspace/PR_BUILD.txt)" == "false" ]; then
      gcloud run deploy instruct-multilingual-frontend-staging \
        --image gcr.io/$PROJECT_ID/frontend:$SHORT_SHA \
        --project $PROJECT_ID \
        --region ${_REGION} \
        --platform managed \
        --allow-unauthenticated \
        --concurrency 5 \
        --cpu 1 \
        --memory 2Gi \
        --min-instances 2 \
        --max-instances 3 \
        --set-env-vars ENVIRONMENT=staging,BACKEND_URL=https://instruct-multilingual-backend-staging-dtjnk4f6ra-ue.a.run.app
      echo $(gcloud run services describe instruct-multilingual-frontend-staging --platform managed --region ${_REGION} --format 'value(status.url)') > /workspace/FRONTEND_URL.txt
    fi
  id: 'deploy-frontend-staging'
  timeout: '600s'

# Update the backend with the correct FRONTEND_URL
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [ "$(cat /workspace/PR_BUILD.txt)" == "false" ]; then
      gcloud run services update instruct-multilingual-backend-staging \
        --region ${_REGION} \
        --platform managed \
        --update-env-vars FRONTEND_URL="$(cat /workspace/FRONTEND_URL.txt)"
    fi
  id: 'update-backend-frontend-url-staging'
  
